# docker-compose.yml
version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4
    ports:
      - "27018:27017"  # Changer le port externe à 27018 pour éviter les conflits
    volumes:
      - ./database:/data/db
      